import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# OpenAI API Configuration
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
MODEL_NAME = "gpt-4o"  # gpt-4o, gpt-4, gpt-3.5-turbo
MAX_TOKENS = 2000
# Temperature is a parameter that controls the “creativity” or randomness
# of the text generated by GPT-3. A higher temperature (e.g., 0.7) results
# in more diverse and creative output, while a lower temperature (e.g., 0.2)
# makes the output more deterministic and focused.
TEMPERATURE = 0.2

# Other imports and configurations
TOPICS = ["Introduction to ANOVA", "Types of ANOVA", "ANOVA Assumptions"]

# Tone Dictionary Based on Content Creators
TONE_DICTIONARY = {
    "sentdex": "The tone should be technical and educational, with a clear step-by-step coding walkthrough, including practical examples and explanations for each step",
    "kyla": "Use relatable analogies and storytelling to simplify the topic, making the content accessible and interesting to a general audience"
}

# Select the content creator's tone you want to use
CONTENT_CREATOR = "kyla"
TONE = TONE_DICTIONARY.get(CONTENT_CREATOR)

# Optional example to be included
EXAMPLE = "Baking cookies"

# Series Configuration
IS_SERIES = True
SERIES_TITLE = "ANOVA Explained"  # Title of the series
SERIES_PART = ["Part 1", "Part 2", "Part 3"]  # Titles for each part of the series


# Blog Post Structure with Conditional Example and Tone Included
BLOG_POST_STRUCTURE = {
    "introduction": lambda topic: construct_prompt("Write an engaging introduction about", topic),
    "body": lambda topic: construct_prompt("Provide detailed information and analysis on", topic),
    "conclusion": lambda topic: construct_prompt("Summarize the key points and provide a concluding thought about", topic)
}

# Video Script Structure with Conditional Example and Tone Included
VIDEO_SCRIPT_STRUCTURE = {
    "intro": lambda topic: construct_prompt("Create an engaging introduction for a video about", topic),
    "key_points": lambda topic: construct_prompt("Outline the main points that will be discussed in a video about", topic),
    "summary": lambda topic: construct_prompt("Provide a concise summary of the content covered in the video about", topic)
}
