import unittest
from unittest.mock import patch
from generators.blog_post_generator import generate_outline, generate_content, format_blog_post


class TestBlogPostGenerator(unittest.TestCase):
    """
    Unit tests for the blog post generation functions.
    """

    def test_generate_outline_valid_topic(self):
        """
        Test that generate_outline returns a structured outline when given a valid topic.

        This test verifies that the generate_outline function returns a dictionary with keys 'introduction',
        'body', and 'conclusion' when provided with a valid topic.
        """
        topic = "Introduction to ANOVA"
        outline = generate_outline(topic)

        expected_keys = ['introduction', 'body', 'conclusion']
        self.assertIsInstance(outline, dict)
        self.assertTrue(all(key in outline for key in expected_keys))
        self.assertTrue(all(outline[key] == "" for key in expected_keys))

    def test_generate_outline_empty_topic(self):
        """
        Test that generate_outline returns an empty dictionary when given an empty topic.

        This test checks that the generate_outline function returns an empty dictionary if the topic string is empty.
        """
        topic = ""
        outline = generate_outline(topic)

        self.assertEqual(outline, {})

    @patch("generators.blog_post_generator.GPTClient.generate_text")
    def test_generate_content_valid_outline(self, mock_generate_text):
        """
        Test that generate_content returns filled content for a valid outline.

        This test mocks the GPTClient to simulate API responses and verifies that the generate_content function
        correctly fills the outline with content generated by the API.
        """
        mock_generate_text.side_effect = [
            "This is the introduction.",
            "This is the body.",
            "This is the conclusion."
        ]

        outline = {
            'introduction': '',
            'body': '',
            'conclusion': ''
        }
        topic = "Introduction to ANOVA"
        content = generate_content(outline, topic)

        self.assertIsInstance(content, dict)
        self.assertEqual(content['introduction'], "This is the introduction.")
        self.assertEqual(content['body'], "This is the body.")
        self.assertEqual(content['conclusion'], "This is the conclusion.")

    @patch("generators.blog_post_generator.GPTClient.generate_text")
    def test_generate_content_empty_outline(self, mock_generate_text):
        """
        Test that generate_content returns an empty dictionary when given an empty outline.

        This test verifies that if the outline is empty, the generate_content function does not make any API calls
        and returns an empty dictionary.
        """
        outline = {}
        topic = "Introduction to ANOVA"
        content = generate_content(outline, topic)

        mock_generate_text.assert_not_called()
        self.assertEqual(content, {})

    def test_format_blog_post_valid_content(self):
        """
        Test that format_blog_post returns a properly formatted blog post when given valid content.

        This test verifies that the format_blog_post function correctly formats the content into a structured blog post.
        """
        content = {
            'introduction': "This is the introduction.",
            'body': "This is the body.",
            'conclusion': "This is the conclusion."
        }
        formatted_post = format_blog_post(content)

        self.assertIsInstance(formatted_post, str)
        self.assertIn("Introduction:", formatted_post)
        self.assertIn("This is the introduction.", formatted_post)
        self.assertIn("Body:", formatted_post)
        self.assertIn("This is the body.", formatted_post)
        self.assertIn("Conclusion:", formatted_post)
        self.assertIn("This is the conclusion.", formatted_post)

    def test_format_blog_post_empty_content(self):
        """
        Test that format_blog_post returns an empty string when given empty content.

        This test verifies that the format_blog_post function returns an empty string if the content dictionary is empty.
        """
        content = {}
        formatted_post = format_blog_post(content)

        self.assertEqual(formatted_post, "")


if __name__ == '__main__':
    unittest.main()
